Add typescript typings
fluture-js/fluture-retry pull request #15
Opened 2019-11-10 02:01 UTC by EricCrosson

Hello, nifty project! Thanks for your work on fluture-retry and fluture as a whole. 

This PR adds typescript typings, which I have tested by publishing to a local npm-registry under a scoped namespace and installed and successfully used from a typescript package.

I am unable to get `npm test` to pass, the `lint` run-script fails with message

```
node_modules/.bin/sanctuary-generate-readme: line 33: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
events.js:187
      throw er; // Unhandled 'error' event
```

however on my machine this also occurs on the unchanged master branch and I do not think this breakage was introduced by my changes. 

I'm more than happy to address any feedback.

Please note I have not bumped any npm versions so that will have to be done manually before publishing these updates to npm.

Thanks again for publishing fluture-retry!

2019-11-10 02:05 UTC, EricCrosson commented
Well travis passes, that makes me feel better

2019-11-10 21:08 UTC, davidchambers commented
Thanks for the contribution, @EricCrosson!

`declare -A` was added in [Bash 4][1], released in 2009. On macOS one can run `brew install bash` to install a compatible Bash version.


[1]: https://www.tldp.org/LDP/abs/html/bashver4.html

2019-11-11 00:29 UTC, EricCrosson commented
Thanks for the tip! After `brew install bash` the tests all pass on my mac

2019-11-11 00:29 UTC, davidchambers commented
Excellent! I'll let Aldwin review the changes. :)

2019-11-11 15:33 UTC, Avaq requested changes
This is excellent! Thank you. I suggest one minor change to make the signature of retry just that tiny bit more self-documenting.

2019-11-11 15:33 UTC, Avaq commented on index.d.ts
> +declare function retry(time: (a: number) => number): (max: number) => <A, B>(task: Future.FutureInstance<A, B>) => Future.FutureInstance<A[], B>;
```suggestion
declare function retry(time: (tries: number) => number): (max: number) => <A, B>(task: Future.FutureInstance<A, B>) => Future.FutureInstance<A[], B>;
```

2019-11-11 16:17 UTC, EricCrosson commented
Good call! Thanks for queueing up the change

2019-11-11 16:31 UTC, Avaq approved these changes

2019-11-17 09:38 UTC, closed without merging